<?php
/* @var $generator yii\gii\generators\model\Generator */
$ns = explode('\\', $generator->moduleClass)[0];
?>
<?= "<?php" ?>

namespace <?= $ns ?>\<?= $generator->moduleID ?>\components;

use backend\components\MyController;

class My<?= ucfirst($generator->moduleID) ?>Controller extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
